"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-05-10 01:23:35.327168

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('input_data_json', sa.Text(), nullable=False),
    sa.Column('response_markdown', sa.Text(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_analyses', schema=None) as batch_op:
        batch_op.create_index(
            'ix_ai_analyses_ticker_expires', ['ticker', 'expires_at'], unique=False,
        )

    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('daily_recaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recap_date', sa.Date(), nullable=False),
    sa.Column('market_summary_json', sa.Text(), nullable=True),
    sa.Column('watchlist_performance_json', sa.Text(), nullable=True),
    sa.Column('news_summary_json', sa.Text(), nullable=True),
    sa.Column('ai_commentary_text', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generation_status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recap_date')
    )
    op.create_table('news_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'url', name='uq_news_ticker_url')
    )
    with op.batch_alter_table('news_cache', schema=None) as batch_op:
        batch_op.create_index(
            'ix_news_cache_ticker_published_at', ['ticker', 'published_at'], unique=False,
        )

    op.create_table('price_cache',
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'date')
    )
    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_items')
    op.drop_table('price_cache')
    with op.batch_alter_table('news_cache', schema=None) as batch_op:
        batch_op.drop_index('ix_news_cache_ticker_published_at')

    op.drop_table('news_cache')
    op.drop_table('daily_recaps')
    op.drop_table('app_settings')
    with op.batch_alter_table('ai_analyses', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_analyses_ticker_expires')

    op.drop_table('ai_analyses')
    # ### end Alembic commands ###
